name: demo deploy pipeline

on:
  workflow_dispatch:

jobs:
  demo-deploy:
    runs-on: ubuntu-latest
    env:
      EC2_URL: ${{ secrets.EC2_URL }}
      EC2_USERNAME: ${{ secrets.EC2_USERNAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          printf '%s\n' "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Test SSH connection and create hello-world file
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }} "
            echo 'SSH Connected ✅' && echo 'hello-world' >> ~/new_file.txt
          "

      - name: Clone or pull repo on EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }} "
            if [ ! -d ~/project ]; then
              git clone https://github.com/srinivasarao3234/workflow-testing.git ~/project;
            else
              cd ~/project && git pull;
            fi
          "

      - name: Upload demo .env
        run: |
          echo "APP_ADMIN_USERNAME=demoadmin" > .env
          echo "APP_ADMIN_PASSWORD=demopass" >> .env
          echo "DB_USERNAME=demouser" >> .env
          echo "DB_PASSWORD=demopass" >> .env
          scp -o StrictHostKeyChecking=no -i private_key.pem .env ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }}:~/project/.env

      - name: Run demo Docker container
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_URL }} "
            docker run --rm hello-world
          "
